### ISSUE TITLE
Librecaptcha in Joomla?

### ISSUE THREAD

**Issue by sorgina** [nickolas360/librecaptcha#3]
Hello
I am a Joomla user and have just discovered Librecaptcha. Do you give the opportunity to install Librecaptcha in Joomla?

**Comment by nickolas360** [comment]
No, as a Python package, that wouldn't exactly make sense. I am, however, planning on writing a JavaScript port of librecaptcha, which would be more suitable for the web.

**Comment by sorgina** [comment]
Thank you for the info.
